aagateway:
  host: https://aagateway.onrender.com #指令钱包服务地址
mail:
  host: <my email pop3 server>
  tls: true
  port: 995
  user: <MASK>
  password: <MASK>
  db:
    type: pgsql # supports: pgsql or sqlite
    connection: <DB Connection String>